### ISSUE TITLE
OSD not adjust to the screen after playback

### ISSUE THREAD

**Issue by CodingPoeta** [bri3d/msp-osd#103]
Hi guys, Thanks for what you have done for the fpv community.

I have found a little bug with msp-osd,

# OSD doesn't adjust to the screen

<img width="584" alt="Screenshot 2023-01-20 at 5 47 02 PM" src="https://user-images.githubusercontent.com/24382556/213665391-2ac6d08a-f914-48b1-9be6-46aada6b28e9.png">

If I go view the playbacks when the air unit still connected, the OSD must be broken like above. The only way to recover is restart both goggles and air unit.

It's actually not a big problem because I guess nobody gonna open a playback while flying hahaha...

**Comment by hickscorp** [comment]
Could this be related to https://github.com/fpv-wtf/msp-osd/issues/104 ?

I too have to restart both devices in a very specific order once it glitches.

**Comment by bri3d** [comment]
This should have been fixed in https://github.com/fpv-wtf/msp-osd/releases/tag/v0.10.0 . Please re-open if it's not fixed in 0.10.0
