### ISSUE TITLE
OSD resolution glitches.

### ISSUE THREAD

**Issue by hickscorp** [bri3d/msp-osd#104]
I've been kindly pointed to this issue tracker.

The summary for this issue is here: https://github.com/fpv-wtf/wtfos/issues/57

It seems that this is the more appropriate place for it.

Thanks @bri3d !

**Comment by bri3d** [comment]
Use the `compress_osd` `package-config` setting on the air (Vista/AU) side.

**Comment by t0ffi** [comment]
Same issue occur for me. OSD looks like on screenshot below: 

![OSD configurator in BF](https://cdn.discordapp.com/attachments/1011767968583139429/1066706450392567889/image.png)

Preview in gogles looks like: 

![Gogles preview](https://cdn.discordapp.com/attachments/1011767968583139429/1066711034091544658/20230122_142755.jpg)

I did `compress_osd` `package-config` and didn't resolve this issue also reinstalled wtf.os both on gogles and air side.

**Comment by hickscorp** [comment]
@bri3d I've done a couple of flights today and it seems to have worked. Thanks for the pointers! I'll leave the conversation open as it might be a relevant report @t0ffi brought into it.

**Comment by t0ffi** [comment]
Problem solved. I've connected battery to drone, connected to BF configurator and adjusted OSD in "real time" and OSD elements moved to proper postion.

**Comment by bri3d** [comment]
Yes, this makes sense as well. Unfortunately the overall grid size is not persistent in Betaflight, it is set by a negotiation each boot. So both the FC and VTx need to be turned on for the grid size to match. 

I'm closing this ticket as both issues are now resolved.

**Comment by FurioMan** [comment]
Hi Guys,

Got a problem with one of my quads with Vista (on og air units it works well).
I see HD option in OSD menu, but I can't mark it. When I click it, it goes back to auto instantly.
In the google's I have the HD fonts and the readings from LQ and others and they are are working well, but whole HD osd is on SD grid, so showing itself in the googles, in the top left part of a screen.  I've already re-rooted the Vista, reinstalled WTFOS. Let me know what you think.

![image](https://github.com/fpv-wtf/msp-osd/assets/138247739/3e7f85e6-a8cf-4ee3-a27d-b5fe1372da43)

![image](https://github.com/fpv-wtf/msp-osd/assets/138247739/597a03e2-0238-4e4e-a305-016c9f38a8c5)

**Comment by j005u** [comment]
> Hi Guys,
> 
> Got a problem with one of my quads with Vista (on og air units it works well). I see HD option in OSD menu, but I can't mark it. When I click it, it goes back to auto instantly. In the google's I have the HD fonts and the readings from LQ and others and they are are working well, but whole HD osd is on SD grid, so showing itself in the googles, in the top left part of a screen. I've already re-rooted the Vista, reinstalled WTFOS. Let me know what you think.
> 
> ![image](https://user-images.githubusercontent.com/138247739/250169942-3e7f85e6-a8cf-4ee3-a27d-b5fe1372da43.png)
> 
> ![image](https://user-images.githubusercontent.com/138247739/250168128-597a03e2-0238-4e4e-a305-016c9f38a8c5.png)

Check that your UART is working both ways. This can happen if only one of the two wires is working.

One way to check in the Goggles is to see if the goggles can display your quads voltage. If it cannot then the UART connection is faulty.
