### ISSUE TITLE
Goggles are splitting videos > 10 minutes, but there's only one OSD file

### ISSUE THREAD

**Issue by wessi86** [bri3d/msp-osd#109]
The FPV Goggles V2 are splitting files > 10 minutes so on a long range flight you would have several clips but only one OSD files is being created. Stitching the videofiles together doesn't work.

**Comment by j005u** [comment]
For the time being the fix is to disable overwrite loop recording on the Goggles. This results in the video files no longer being split and the .osd-s matching properly.

**Comment by wessi86** [comment]
> For the time being the fix is to disable overwrite loop recording on the Goggles. This results in the video files no longer being split and the .osd-s matching properly.

This worked, thanks a lot!
