### ISSUE TITLE
disable_betaflight_hd is undefined in schemaV2.json

### ISSUE THREAD

**Issue by j005u** [bri3d/msp-osd#113]
![image](https://user-images.githubusercontent.com/457157/230788005-cd72eb78-d8cf-412a-b02a-c887fe97970b.png)

Looks like disable_betaflight_hd  was only added to schema.json.

Technically schema.json can be dropped, as long as package-config isn't actually used.

**Comment by bri3d** [comment]
https://github.com/fpv-wtf/msp-osd/blob/main/config/airunit/schemaV2.json#L44 erm?

**Comment by j005u** [comment]
> https://github.com/fpv-wtf/msp-osd/blob/main/config/airunit/schemaV2.json#L44 erm?

Erm indeed. I saw two people post screenshots with the same issue (no name or description) and presumed it's undefined.

Will dig out a vista and try to repro.

**Comment by bri3d** [comment]
I can take a look too, my first thought was some kind of issue parsing the descriptor, but it looks right on a cursory glance. Weird.

**Comment by j005u** [comment]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/457157/230792347-c706c0d8-7b81-4f9f-bab0-be33011a064e.png">

But le why..?

**Comment by j005u** [comment]
Pinging @stylesuxx about the above issue.

Any idea what we're missing? Why doesn't the disable_betaflight_hd setting get rendered correctly?

I was able to repro on my Vista, but nothing useful in console and the schema file looks correct indeed.

**Comment by j005u** [comment]
Derp herp, hurr durr. Totally missed it the first 3 times.

"name" - "title".

Also for osd_update_rate_hz.

This can be helpful for sanity checks: https://rjsf-team.github.io/react-jsonschema-form/

**Comment by benlumley** [comment]
Has been fixed (by bri, not me!)
