### ISSUE TITLE
fakehd_hide_throttle_element vs  fakehd_hide_menu_switch

### ISSUE THREAD

**Issue by xviews** [bri3d/msp-osd#116]
Hey
fakehd_hide_menu_switch does "FakeHD will hide the menu switch set above; and the next 5 characters" but what does the new fakehd_hide_throttle_element command do? In the glasses Betaflight Throttle disappears only with fakehd_menu_switch

**Comment by benlumley** [comment]
fakehd_hide_throttle_element was the original / early name of fakehd_hide_menu_switch; it was renamed when the menu switch character became configurable; you should use that instead.
