### ISSUE TITLE
Swap to Goggles GUI without uninstalling MSP OSD?

### ISSUE THREAD

**Issue by Revvilo** [bri3d/msp-osd#118]
Forgive me if I'm blind, but I've searched and can't find any mention of this.
It seems that while the package is installed, the OSD is always active and totally hides the DJI Goggle GUI, even though it can still be interacted with.
I find myself wanting to change transmission settings, camera configurations, etc while in the field. Is it possible to access the DJI Goggles interface without having to uninstall the MSP OSD package?

**Comment by j005u** [comment]
That's not normal.

If you uninstall msp-osd you should be able to access the original menus for checking things.

Could you please 1) check what fw version you are on and report back and b) restore the goggles using butter and re-install https://github.com/fpv-wtf/butter#usage

The problem should hopefully go away.

**Comment by Revvilo** [comment]
Sorry, I might have caused some confusion.

Yes, uninstalling msp-osd allows me to access the DJI interface.

What I'm asking is if it is possible to switch to the goggle menus without removing the msp-osd package.

Edit: I'm running V01.00.0604

**Comment by Revvilo** [comment]
Oh wait, I misunderstood. Using butter to update the goggles to firmware V01.00.0606, and then installing WTFOS again as normal along with the packages now shows both the msp-osd and the DJI interface!

Here I was thinking it was a trade-off, lmao. Hopefully this will serve useful to other travellers.

Thank you :)
