### ISSUE TITLE
.osd files with Googles V2 and DJI O3 unit?

### ISSUE THREAD

**Issue by vedmant** [bri3d/msp-osd#133]
Is there a way to record .osd file when using Googles V2 and DJI O3 unit?

**Comment by j005u** [comment]
There isn't as the O3 software is completely different from the old Air Unit software. msp-osd does not (and cannot) run in O3 mode and therefor cannot add .osd recording.

It's technically possible to add .osd recording to the O3 side as a completely separate project, but no devs have stepped up to invest their time into it yet.
