### ISSUE TITLE
Tx uplink Power OSD element is not working

### ISSUE THREAD

**Issue by lmc2** [bri3d/msp-osd#144]
the "Tpwr" or also called "Tx uplink Power" OSD element is not working in Betaflight.
Vista and V1 Googles, latest WTF firmware, tested on BF 4.4.2 and 4.5

**Comment by bri3d** [comment]
The WTFOS msp-osd has no way to know what elements it is displaying; it just draws what the FC sends it. 

A few things to check:

* Is your Tx/Rx system configured in a way that Tx Uplink Power should work? (for example, on ELRS, it doesn't work with `Hybrid` switch mode?).
* On Betaflight 4.5, try `set displayport_msp_fonts = 0,0,0,0` to make sure that warnings don't get rendered with an unsupported font page. But if you tried 4.4.2, that's probably not it.

**Comment by lmc2** [comment]
Thank you so much !!!!!! i totaly forgott about the switch mode! it works :)
