### ISSUE TITLE
Goggles stuck on wait for data if Air Unit/Vista is turned on before Goggles enter MSP mode

### ISSUE THREAD

**Issue by fabriciopolonio** [bri3d/msp-osd#18]
The order in which we start the msp-ods and goggles seems to affect first usage.

If we do plug the battery on quad and power on Air Unit/Vista, then enter the msp-osd mode, the goggles get stuck waiting for data, then it is required to turn off Air Unit/Vista and turn on again to get it working.

Not clear yet if this is an issue on the goggles side or the air unit/vista.

**Comment by bri3d** [comment]
Please try again with the latest version - recent reports indicate this may be fixed with the latest version.

**Comment by bri3d** [comment]
I think this should be fixed
