### ISSUE TITLE
Msp-osd in Inav

### ISSUE THREAD

**Issue by Ben-Stevenss** [bri3d/msp-osd#26]
In the ports tab you have to select hdzero, does the msp also need to be switched on?

somehow i can’t seem to switch msp and hdzero on together. 

I have the osd working/running but the elements are wrong/messed up. Some are ok bu tmost are not. 
and yes i tried going in the menu with stick command and back.

**Comment by bri3d** [comment]
No, MSP should not also be switched on, just HDZero VTx.

What fonts do you have on your SD card, if any?

**Comment by Ben-Stevenss** [comment]
Impact mini renamed to font. 

But the one from the betaflight folder. 
Did a couple of betaflight quads, and a few days later tried my inav wing. Can try the inav font?

**Comment by bri3d** [comment]
Yes, this will be why, then. Need to use font corresponding to FC in use. I will add a feature to ID the FC and use different fonts at some point soon here.

**Comment by Ben-Stevenss** [comment]
So at the moment i can't use betaflight and inav together?

**Comment by bri3d** [comment]
One trick for this is to use iNav in HD mode, and use an iNav font as the HD font (font_hd and font_hd_2) on the SD card. Then leave your "normal" font as a Betaflight one.

**Comment by bri3d** [comment]
Down the road, I plan to add FC detection to determine which fonts to use.
