### ISSUE TITLE
"Waiting for OSD" Message

### ISSUE THREAD

**Issue by Kallepitch** [bri3d/msp-osd#31]
Hey guys,
 I got on UART 1 my VTX so which "displayport_msp_serial" should I set then?
I set displayport_msp_serial = 5 and still get the message "OSD WAITING"

**Comment by eva-val** [comment]
The docs say to set it to ConfiguratorUART - 1 so try
displayport_msp_serial = 0

**Comment by Kallepitch** [comment]
Works fine now. Many thanks =)
