### ISSUE TITLE
Support for Emuflight

### ISSUE THREAD

**Issue by DiehardFPV** [bri3d/msp-osd#34]
Hola~ developers, your work is brilliant but i noticed i was unable to use this feature on my Emuflight drones
 I wonder is it possible to support Emuflight osd（If that's not a lot of work）？

**Comment by bri3d** [comment]
Does EmuFlight support MSP DisplayPort? If so, msp-osd should work. If not, it won't.

**Comment by DiehardFPV** [comment]
Unfortunately😔, it doesn't

**Comment by SebastianKumor** [comment]
@DiehardFPV @bri3d I think new emu 0.4.2 will https://github.com/emuflight/EmuFlight/pull/775
