### ISSUE TITLE
Is there a font-preview of the fonts inside mcm2img-fonts.tar.gz ?

### ISSUE THREAD

**Issue by AndKe** [bri3d/msp-osd#41]
the subject says it all, it would be very nice to be able to check out the fonts side-by-side. (some screenshots)

**Comment by bri3d** [comment]
No but that's a good idea. I'll consider adding PNG export side by side also

**Comment by AndKe** [comment]
Thank you - in the meantime - which font do you recommend for good readability & look? (for Betaflight)

**Comment by benlumley** [comment]
You can preview them all in BF configurator on the OSD tab, under Font Manager.

**Comment by AndKe** [comment]
thank you ! :)
