### ISSUE TITLE
Save framebuffer to file.

### ISSUE THREAD

**Issue by cvetaevvitaliy** [bri3d/msp-osd#47]
Hi! Very cool project, thanks to everyone who contributed!

I have an idea, what if we take the data that comes into the framebuffer and save it ?
This will allow us to have video with OSD data.

example save framebufer to file 
`ffmpeg -f fbdev -framerate 25 -i /dev/fb0 output.avi`

I see package `ffmpeg` utility  in Package Manager

**Comment by bri3d** [comment]
A few notes:

* The framebuffers used in DJI are never exposed to the Linux `fbdev` framebuffer infrastructure - they're all allocated internally and managed through the DJI `libduml_hal` driver. 
* Video with OSD data composited onto it never exists in a framebuffer that is exposed in any known way. The video stream from the VTx (or playback) is decoded in the RTOS running on the CP (coprocessor) CPU and is sent directly to the screen from there. Overlay layers like the DJI menus and OSD are produced on the AP (Application Processor) CPU and sent to the CP (Coprocessor) CPU using shared memory and ICC (Inter Core Communication).
* Based on disassembly of the Coprocessor RTOS, it seems that the layers are actually blended in hardware at the LCDC (LCD Controller). So, as far as we know a composited screen buffer - that is, a set of pixel data that includes both the video feed and the OSD, doesn't exist in RAM that's accessible to the CPU at all. One experiment here could be to dump all of RAM to see if the LCD Controller also has a shared RAM area that perhaps it is using as a render target, although it's equally likely that it has a final framebuffer which is internal to the LCD Controller. 

My intended solution to this is to dump out the MSP OSD data into a file while video is being recorded (the main issue here is time sync, which is annoying but certainly a solvable problem). 

Once the MSP OSD data is in a file, we can write a PC application where we have plenty of CPU and encoding power which can draw the OSD again, composite the video, and render it out into a new file.

**Comment by cvetaevvitaliy** [comment]
> 

Hi! Yes you’re right in the frame buffer does not store the image that is transmitted from the AirUnit.
I added libpng to the project and saved the current frame to a file, there I see only OSD data without an image from the AirUnit.

And I thought, maybe make feature:  take screenshot on back button click 😁


![image_15](https://user-images.githubusercontent.com/26421560/189350751-f8dc0984-956a-4b84-b8aa-a0a342532cf9.png)

**Comment by cvetaevvitaliy** [comment]
> 
but about saving MSP data to a file, it's possible.  The trigger to start recording can be an ARM command in an MSP frame, goggle also start recording after ARM on, synchronization can be done manually (maximum 0.5-1s desynchronization)

**Comment by cvetaevvitaliy** [comment]
Test saved MSP data from from DJI FPV

A little later I will amke commit and PR to your repo

UPDATE: please check your path to the SD card, my path is `/mnt/media_rw/79CC-CB2A` I hope these magic numbers along the path are not unique for each instance :D

[data.msp.zip](https://github.com/fpv-wtf/msp-osd/files/9538985/data.msp.zip)

<img width="1261" alt="ScreenShot 2022-09-10 в 01 04 05" src="https://user-images.githubusercontent.com/26421560/189452408-127c01a2-e5c0-4ed9-8c06-ad8723d7aaea.png">

**Comment by j005u** [comment]
@cvetaevvitaliy mine is /mnt/media_rw/08F6-9CDC

Use the /storage/sdcard0 symlink instead. You can also check for the presence of the link to make sure the sdcard is mounted.

Protip: you can use `setprop persist.dji.storage.exportable 0` do disable unmounting the SD card from the Goggles while connected to PC for adb.

**Comment by FPVZaphod** [comment]
It would be cool already to save MSP Data to a file, and then having a tool to render an OSD out of it, and overlay it to the video afterwards. Luxurity would be a 2nd video file, only with OSD, to just mix them afterwards :-)

**Comment by bri3d** [comment]
Knifa added MSP data saving a few versions ago
