### ISSUE TITLE
Any chance the "Waiting for OSD..." message could be removed?

### ISSUE THREAD

**Issue by ramiss** [bri3d/msp-osd#51]
Any chance the "Waiting for OSD..." message could be removed for those of us that like the option of using the old DJI Custom OSD for FC's such as Ardupilot, but want this option for BF builds?   What would be really slick is if the message went away when Custom OSD is turned on.

**Comment by benlumley** [comment]
It's on the list / coming as a configurable thing.

**Comment by bri3d** [comment]
Now configurable as of v0.6.4.

Upgrade to v0.6.4 or later.

Enter the CLI tab with the Goggles connected.

`package-config set msp-osd show_waiting false`
`package-config apply msp-osd`

v0.6.5 will be up on the opkg repo within the next 10mins or so.
