### ISSUE TITLE
Temp AU on Google not showen 

### ISSUE THREAD

**Issue by toto73** [bri3d/msp-osd#56]
I take the new Update 0.6.5 on the Google and to the Vista.
Now i can t see the Temperatur from the AirUnit in the osd.
In configurator cli is Status au data true.
At Firmware 0.6.3 its have work.

**Comment by bri3d** [comment]
Please refer to https://github.com/fpv-wtf/msp-osd#configuration-options

Plugging the goggles into WTFOS Configurator, clicking to CLI tab, and typing:

```
package-config set msp-osd show_au_data true
package-config apply msp-osd

```

 should work for you.
