### ISSUE TITLE
Missing OSD elements

### ISSUE THREAD

**Issue by dataema92** [bri3d/msp-osd#62]
Hello, with the last updets i noticed that some OSD elements are missing. For example the satellite count is missing.
Can anyone help me?
Thank you

here you can find some photos of the problem
https://postimg.cc/PLxcHzmp
https://postimg.cc/PvmVy6kc

**Comment by benlumley** [comment]
i think this is a betaflight issue.... is your gps connected / working  ?

**Comment by dataema92** [comment]
Yes. The GPS is working fine

**Comment by dataema92** [comment]
it was the GPS configuration. Thank you very much!
