### ISSUE TITLE
when msp_displayport_mux started, channel number not updated when channel was change by user

### ISSUE THREAD

**Issue by singlag** [bri3d/msp-osd#7]
when msp_displayport_mux started at airunit, channel number not updated when channel was change by user

1) setup auto start msp_displayport_mux at Airunit
adb shell echo "'sleep 15' >> /system/bin/dji_setup_uart.sh"
adb shell echo "'./blackbox/start_msp.sh &' >> /system/bin/dji_setup_uart.sh"

start_msp.sh :
setprop dji.hdvt_uav_service 0
mv /dev/ttyS1 /dev/ttyS1_moved
nohup /blackbox/msp_displayport_mux 192.168.41.2 /dev/ttyS1_moved /dev/ttyS1 &

2) setup auto start osd_dji at Goggles
adb shell echo "'sleep 15' >> /system/bin/dji_setup_uart.sh"
adb shell echo "'./blackbox/start_osd.sh &' >> /system/bin/dji_setup_uart.sh"

start_osd.sh :
nohup /blackbox/osd_dji &

3) power up both devices, msp_displayport_mux  and osd_dji started
before hold the BACK button for 5 seconds to start MSP OSD, use DJI gui or press button to change channel, it should be changed to new channel, but the gui still showing existing channel number, need to reboot both device and "new" channel number is updated

if msp_displayport_mux at Airunit is not started(auto or manual), channel number will update at goggles GUI

startup script:
https://github.com/singlag/msp-osd/tree/main/msp_osd_installer

**Comment by bri3d** [comment]
You just need to add `setprop dji.hdvt_uav_service 1` to restart the UAV service which runs the radio commands on the air side.

This will also restart the DJI OSD MSP commands (even if you disable the DJI OSD, it still sends them), which might or might not make your DisplayPort OSD unacceptably slow as well.

I am going to add a feature soon to the serial mux to try to add fake responses and reduce the load presented by the DJI spam (and allow for platforms like Ardupilot where a serial port can't be DisplayPort and request/response MSP at the same time).

There are several features like this which I wanted to add before I started shipping releases.

p.s. did you talk to @j005u about installers? He is also working on something for margerine in general.
