### ISSUE TITLE
fakehd_lock_center

### ISSUE THREAD

**Issue by gavris07** [bri3d/msp-osd#70]
package-config set msp-osd fakehd_lock_center true

 does not work

All the same, gaps in the OSD, but I don't need them

**Comment by bri3d** [comment]
It's unclear what you are saying.

Can you paste the output of `package-config get msp-osd` ?

**Comment by gavris07** [comment]
Here's the answer
root@pigeon_wm150_gls:/ # package-config get msp-osd
show_waiting='true'
show_au_data='false'
fakehd_enable='true'
fakehd_hide_throttle_element='false'
fakehd_lock_center='true'

**Comment by gavris07** [comment]
after reloading the glasses gives this
root@pigeon_wm150_gls:/ # package-config get msp-osd
show_waiting='true'
show_au_data='false'
fakehd_enable='true'
fakehd_hide_throttle_element='false'
fakehd_lock_center='false'

**Comment by gavris07** [comment]
made a reroute, the glasses began to save the settings, the topic can be closed))
