### ISSUE TITLE
Invalid key for msp-osd for show_au_data option

### ISSUE THREAD

**Issue by Alastorru** [bri3d/msp-osd#74]
Running msp-osd 0.6.10 on goggles v2, trying to set show_au_data on true, got "invalid key for msp-osd" message, and the option does not chnge.
![image](https://user-images.githubusercontent.com/92805657/194304671-e7dbe5b2-0e51-4ed6-98e7-11d90f8c167d.png)

**Comment by bri3d** [comment]
This is a bug, thanks for reporting. Will be fixed in the next release.
