### ISSUE TITLE
fakehd_hide_menu_switch do not work

### ISSUE THREAD

**Issue by druckgott** [bri3d/msp-osd#82]
Hallo, I aktivate:

```
package-config set msp-osd fakehd_hide_menu_switch true
package-config set msp-osd fakehd_menu_switch 4
package-config apply msp-osd
```
In Betaflight I aktivate: 
![Unbenannt](https://user-images.githubusercontent.com/18383738/197402585-e4a48688-1ac6-4afe-a309-c17817c5dfdf.JPG)

But If I disarm, the overview from betaflight is not fit to the middle. It's stretched like my fakehd fields. Also a friend of my hase same problem. What are we doing wrong? 
I have msp-osd current version installed. (V0.7.2)

**Comment by benlumley** [comment]
Is the throttle element on the osd layout in betaflight?

**Comment by druckgott** [comment]
How does this look like or how can I switch it on?
Ore where can I see which element is what that I can maybe change the element

**Comment by benlumley** [comment]
![Screenshot 2022-10-24 at 10 20 12](https://user-images.githubusercontent.com/194052/197493025-ad1c1c12-0b2d-4f5b-a16f-831707af09aa.png)

**Comment by druckgott** [comment]
Ok I changed it like this:
package-config set msp-osd fakehd_hide_menu_switch false
package-config set msp-osd fakehd_menu_switch 137
package-config apply msp-osd

And used the GPS Globe because I did not have Throttle. (instead of: package-config set msp-osd fakehd_menu_switch 4)
![Screenshot_20221024_122615_com android chrome_edit_824226313510688](https://user-images.githubusercontent.com/18383738/197562299-250fdd25-85a6-4103-bce7-7a4a92b2466d.jpg)

Now it´s working, maybe it makes sence to put this example to the readme.
