### ISSUE TITLE
# set osd_displayport_device = MSP ###ERROR### Invalid name

### ISSUE THREAD

**Issue by troppo1** [bri3d/msp-osd#93]
I get this error
###ERROR### Invalid name
when i type in
# set osd_displayport_device = MSP

configurator 10.8.0

# Betaflight / FURYF4OSD (FY4O) 3.5.1 Sep  8 2018 / 05:21:25 (d9fb5ca13) MSP API: 1.40

Edit: works in Roma L5 with version 4.3.
Is there a work around for my old diatone m515 as i didnt want to touch it. It flies great as it is

**Comment by MindRiderFPV** [comment]
are you on 4.4?

**Comment by troppo1** [comment]
> are you on 4.4?

4.3 on roma l5 working fine.  3.5 on m515. I didnt want to upgrade betaflight on the old m515 . But if no work around i will have to

**Comment by bri3d** [comment]
Betaflight 3.5 does not support MSP DisplayPort
